# Copyright (c) 2023 Bank of Italy
# Distributed under the GNU AGPLv3 software license, see the accompanying COPYING file.

FROM ubuntu:22.04

# toolchain deps
RUN apt update && apt install --no-install-recommends -y \
    autoconf \
    automake \
    bsdextrautils \
    ca-certificates \
    cmake \
    g++ \
    gcc \
    git \
    jq \
    libtool \
    make \
    openssh-client \
    pkg-config \
    python3 \
    xxd \
    zlib1g-dev

# build deps
RUN apt install --no-install-recommends -y \
    libargtable2-dev \
    libboost-filesystem1.74-dev \
    libboost-log1.74-dev \
    libboost-program-options1.74-dev \
    libboost-test1.74-dev \
    libboost-thread1.74-dev \
    libcurl4-openssl-dev \
    libdb5.3++-dev \
    libevent-dev \
    libsqlite3-dev \
    libssl-dev \
    libzmq3-dev \
    swi-prolog

RUN mkdir /itcoin-fbft

WORKDIR /itcoin-fbft

COPY . /itcoin-fbft

RUN mkdir /itcoin-fbft/build

WORKDIR /itcoin-fbft/build

RUN cmake ..

# Put itcoin-core in a dedicated layer.
RUN make itcoin-core-libraries -j $(nproc --ignore=1)

RUN make -j $(nproc --ignore=1)
